/* eslint-disable import/no-dynamic-require, global-require */

import React from 'react';
import { renderToString } from 'react-dom/server';
import { StaticRouter } from 'react-router';

import { renderApp } from '@pd/front/src';

/**
 * @typedef {import('express').Express} Express
 * @typedef {import('express').RequestHandler} RequestHandler
 */

/**
 * @typedef {Object} UniversalMiddlewareProps
 * @property {string} statsPath Path to stats generated by webpack.
 * @property {string} manifestPath Path to manifest generated by webpack.
 */

/**
 * Universal Express middleware.
 *
 * @param {UniversalMiddlewareProps} props Props.
 * @returns {RequestHandler}
 */
export const univeralMiddleware = ({ manifestPath }) => (req, res) => {
  const manifest = require(manifestPath);

  const scriptPaths = ['app.js', 'vendor.app.js', 'styles.js']
    .map(name => manifest[name])
    .filter(Boolean);
  const linkPaths = ['styles.css'].map(name => manifest[name]).filter(Boolean);
  const staticContext = {};

  const html = renderToString(
    <StaticRouter location={req.url} context={staticContext}>
      {renderApp()}
    </StaticRouter>
  );

  res.set('Content-Type', 'text/html');
  res.send(`
  <!doctype html>
  <html lang="en">
    <head>
      ${linkPaths
    .map(path => `<link href="/${path}" rel="stylesheet" type="text/css" />`)
    .join('\n')}
      ${scriptPaths.map(path => `<script src="/${path}"></script>`).join('\n')}
      <title>hola world</title>
    </head>
    <body>
      <div id="app">${html}</div>
    </body>
  </html>
`);
};
